### ISSUE TITLE
Formularion sin submit

### ISSUE THREAD

**Issue by DanBaDo** [JoseLuCG/Curriculum#1]
https://github.com/JoseLuCG/Curriculum/blob/7c777f1e15851e5d4b8caa3ce0e82b83cda2896d/src/contact.html#L19-L39

Los formularios  necesitan algún botón, o mecanismo similar, para ser enviados. La forma clásica de conseguir esto es mediante un `<input type="submit" value="Enviar"/>` o similar.

**Comment by JoseLuCG** [comment]
Problema del botón enviar solucionado.
